### ISSUE TITLE
LVM hang up always

### ISSUE THREAD

**Issue by kevinwd** [lvmteam/lvm2#27] opened 2020-04-08 09:28 UTC
![image](https://user-images.githubusercontent.com/29305054/78768286-4f55ed80-79be-11ea-9449-843640b0b354.png)

![image](https://user-images.githubusercontent.com/29305054/78768305-554bce80-79be-11ea-9121-425d834db15b.png)

**Comment by Fredericwu** [comment] 2020-06-05 06:49
root@root:/home/horatio/my-cluster# lvm version
  LVM version:     2.02.176(2) (2017-11-03)
  Library version: 1.02.145 (2017-11-03)
  Driver version:  4.35.0

lvm command always get hang....  Someone encountered the same problem as me？？


![11](https://user-images.githubusercontent.com/41657047/83845313-2db58000-a73b-11ea-80d1-6231059f44f3.png)
![12](https://user-images.githubusercontent.com/41657047/83845327-360dbb00-a73b-11ea-8b91-2257a867d1a2.png)

**Comment by kergon** [comment] 2020-06-05 13:55
lvmetad is not designed to be used in a cluster, where changes might happen on another machine without its knowledge, so I suggest you disable lvmetad.

**Comment by kergon** [comment] 2020-06-05 14:00
You can see it has got stuck trying to scan 8:17 so check if /dev/sdb1 is OK.

**Comment by Fredericwu** [comment] 2020-06-15 14:53
/dev/sdb1 is OK，I test it on other machine.And then i disable lvmetad，the problem is still not solved.
Sorry to reply so late

**Comment by zkabelac** [comment] 2020-06-15 15:48
Hi, can you please provide -vvvv trace of your running command ?
Eventually look for #lvm irc channel on freenode for more interactive help ?

**Comment by zkabelac** [comment] 2020-10-03 20:56
Closing as we have insuficient data and there was no further reaction.

**Closed by zkabelac** 2020-10-03 20:56 UTC
