### ISSUE TITLE
Configure option --enable-lvmlockd-idm broken by commit on 9Jul2021

### ISSUE THREAD

**Issue by TProhofsky** [lvmteam/lvm2#98] opened 2022-12-08 15:13 UTC
The commit on 9 July 2021 removed the declaration of BUILD_LOCKDIDM required for using the --enable-lvmlockd-idm configure option.  See https://sourceware.org/git/?p=lvm2.git;a=commitdiff;h=3a92d633a5a23377aa0d5d4ed5a01db8ca14cf69

Please add it back in.

Thanks.

**Comment by zkabelac** [comment] 2023-02-13 18:23
Thanks for noticing - the issue has been caused by missing AC_SUBST in configure.ac  (fixed by this commit: https://listman.redhat.com/archives/lvm-devel/2023-February/024608.html )
Please retest with latest git HEAD with refreshed  configure file as well - assuming it should be working now again.

**Closed by zkabelac** 2023-02-13 18:23 UTC
